const ADD_NUM = "ADD_NUM";
const SUB_NUM = "SUB_NUM";
const INC_NUM = "INC_NUM";
const DEC_NUM = "DEC_NUM";
const CHANGE_BANNERS = "CHANGE_BANNERS";
const CHANGE_RECOMMENDS = "CHANGE_RECOMMENDS";

export { ADD_NUM, SUB_NUM, INC_NUM, DEC_NUM, CHANGE_BANNERS, CHANGE_RECOMMENDS };
